# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4cef8c4f3c500f963b9c341157dc73db60cbe77db9661efbc130b6a1dfb72ff1e879f3c9b376932449e35a38d9d678b76d276d137b637e619d56dd7524fda9f

test:
  secret_key_base: 6d30616313e302b6be320a44137f5883e0620bf04567f101e0f6daa9bbc70c2c846306cb2d360c842c0f3f513f14e0ab125f6e206bca41f42b93b2ef5ff4a0f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
